CREATE TABLE voting_history(
   ID SERIAL PRIMARY KEY,
   CountyCode            INT     NOT NULL,
   ExtractDate            DATE     NOT NULL,
   LastName        VARCHAR(100)     NOT NULL,
   FirstName        VARCHAR(100)     NOT NULL,
   MiddleName        VARCHAR(100),
   Suffix        VARCHAR(100),
   AddressNumber            INT,
   HouseFractionNumber        VARCHAR(100),
   AddressNumberSuffix        VARCHAR(100),
   StreetDirPrefix        VARCHAR(100),
   StreetName        VARCHAR(100),
   StreetType        VARCHAR(100),
   StreetDirSuffix        VARCHAR(100),
   UnitType        VARCHAR(100),
   UnitNumber        VARCHAR(100),
   City        VARCHAR(100)     NOT NULL,
   State        VARCHAR(100)     NOT NULL,
   Zip        VARCHAR(100)     NOT NULL,
   Phone1Area        VARCHAR(100),
   Phone1Exchange        VARCHAR(100),
   Phone1NumberPart        VARCHAR(100),
   Phone2Area        VARCHAR(100),
   Phone2Exchange        VARCHAR(100),
   Phone2NumberPart        VARCHAR(100),
   Phone3Area        VARCHAR(100),
   Phone3Exchange        VARCHAR(100),
   Phone3NumberPart        VARCHAR(100),
   Phone4Area        VARCHAR(100),
   Phone4Exchange        VARCHAR(100),
   Phone4NumberPart        VARCHAR(100),
   Email        VARCHAR(100),

				


   ElectionType        VARCHAR(100)     NOT NULL,
   ElectionTypeDesc        VARCHAR(100)     NOT NULL,
   ElectionDate            DATE     NOT NULL,
   Method        VARCHAR(100)     NOT NULL,
   RegistrantID            INT     NOT NULL
);