CREATE TABLE registrants(
   ID SERIAL PRIMARY KEY,
   CountyCode            INT     NOT NULL,
   ExtractDate            DATE     NOT NULL,
   LastName        VARCHAR(100)     NOT NULL,
   FirstName        VARCHAR(100)     NOT NULL,
   MiddleName        VARCHAR(100),
   Suffix        VARCHAR(100),
   AddressNumber            VARCHAR(100),
   HouseFractionNumber        VARCHAR(100),
   AddressNumberSuffix        VARCHAR(100),
   StreetDirPrefix        VARCHAR(100),
   StreetName        VARCHAR(100),
   StreetType        VARCHAR(100),
   StreetDirSuffix        VARCHAR(100),
   UnitType        VARCHAR(100),
   UnitNumber        VARCHAR(100),
   City        VARCHAR(100)     NOT NULL,
   State        VARCHAR(100)     NOT NULL,
   Zip        VARCHAR(100)     NOT NULL,
   Phone1Area        VARCHAR(100),
   Phone1Exchange        VARCHAR(100),
   Phone1NumberPart        VARCHAR(100),
   Phone2Area        VARCHAR(100),
   Phone2Exchange        VARCHAR(100),
   Phone2NumberPart        VARCHAR(100),
   Phone3Area        VARCHAR(100),
   Phone3Exchange        VARCHAR(100),
   Phone3NumberPart        VARCHAR(100),
   Phone4Area        VARCHAR(100),
   Phone4Exchange        VARCHAR(100),
   Phone4NumberPart        VARCHAR(100),
   Email        VARCHAR(100),
   MailingAddressLine1        VARCHAR(100),
   MailingAddressLine2        VARCHAR(100),
   MailingAddressLine3        VARCHAR(100),
   MailingCity        VARCHAR(100),
   MailingState        VARCHAR(100),
   MailingZip5        VARCHAR(100),
   MailingCountry        VARCHAR(100),
   Language        VARCHAR(100),
   DOB            DATE     NOT NULL,
   Gender        VARCHAR(100),
   PartyCode        VARCHAR(100)     NOT NULL,
   Status        VARCHAR(100)     NOT NULL,
   RegistrationDate            DATE     NOT NULL,
   Precinct        VARCHAR(100)     NOT NULL,
   PrecinctNumber        VARCHAR(100)     NOT NULL,
   RegistrationMethodCode        VARCHAR(100)     NOT NULL,
   PlaceOfBirth        VARCHAR(100),
   NamePrefix        VARCHAR(100),
   NonStandardAddress        VARCHAR(100),
   VoterStatusReasonCodeDesc        VARCHAR(100)     NOT NULL,
   AssistanceRequestFlag        VARCHAR(100)     NOT NULL,
   VbmVoterType        VARCHAR(100),
   EmsVoterId        INT,
   PrecinctId            INT     NOT NULL,
   RegistrantID            INT     NOT NULL
);